In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
a = (1,2,3,4,5,6)
a

(1, 2, 3, 4, 5, 6)

In [5]:
type(a)

tuple

In [6]:
b= np.array(a)
b

array([1, 2, 3, 4, 5, 6])

In [7]:
type(b)

numpy.ndarray

In [8]:
b.ndim

1

In [9]:
b.shape

(6,)

In [10]:
b.size

6

In [11]:
b.dtype

dtype('int32')

In [12]:
arr = np.array([[4,5,6],[7,8,9]])

print("Array elements are: ",arr)
print("Array is of type: ",type(arr))
print("No. of Dimensions: ",arr.ndim)
print("Array shape: ",arr.shape)
print("Array size: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array elements are:  [[4 5 6]
 [7 8 9]]
Array is of type:  <class 'numpy.ndarray'>
No. of Dimensions:  2
Array shape:  (2, 3)
Array size:  6
Array stores elements of type:  int32


In [13]:
import numpy as arr

In [14]:
a = (1,2,3,4,5,6)
b = arr.array(a)
print(b)

[1 2 3 4 5 6]


In [15]:
import time as tm
import numpy as np

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 5.2166266441345215
numpy = 0.06953072547912598


In [16]:
my_list=[2,3,4,5,6,7,8]
my_list

[2, 3, 4, 5, 6, 7, 8]

In [17]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 5, 6, 7, 8])

In [18]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3 = np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [19]:
array_3.shape

(3, 3)

In [20]:
array_3.size

9

In [21]:
array_3.dtype

dtype('int32')

In [22]:
array_3.ndim

2

In [23]:
a = np.array([1,2,3,4,5,1], ndmin = 2)
print(a)
np.ndim(a)

[[1 2 3 4 5 1]]


2

In [24]:
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [25]:
a = np.array([1,2,3], dtype = int)
print(a)

[1 2 3]


In [26]:
a = np.array([1,2,3], dtype = str)
print(a)

['1' '2' '3']


In [27]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
len(array_3)

3

In [29]:
array_3[2]

array([7, 8, 9])

In [30]:
array_3[0]

array([1, 2, 3])

In [31]:
array_3[2,1]

8

In [32]:
array_3[2,0]

7

In [33]:
array_3[:,1]

array([2, 5, 8])

In [34]:
array_3[:,0]

array([1, 4, 7])

In [35]:
array_3[2:,:]

array([[7, 8, 9]])

In [36]:
array_3[2:,:1]

array([[7]])

In [37]:
array_3[2:,:2]

array([[7, 8]])

In [38]:
array_3[1:,:2]

array([[4, 5],
       [7, 8]])

#Array Atributes

In [39]:
array_3.shape

(3, 3)

In [40]:
my_array.ndim

1

In [41]:
array_3.dtype

dtype('int32')

#Array Initilization

In [42]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(1,10,3)

array([1, 4, 7])

In [44]:
np.arange(1.8,4.8,7.8)

array([1.8])

In [45]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [46]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.zeros(0,dtype=int)

array([], dtype=int32)

In [48]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [49]:
np.zeros(25,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [50]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [51]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [52]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
np.ones((5,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
np.ones((2,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.ones((10,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [56]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [57]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [58]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [59]:
np.linspace(1.23,4.7,10)

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [60]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [62]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [63]:
# Array Initilization with Random Numbers

In [64]:
np.random.rand(2)

array([0.44634152, 0.86596951])

In [65]:
np.random.rand(5)

array([0.99237744, 0.03093275, 0.29815289, 0.70553782, 0.23512282])

In [66]:
np.random.rand(10)

array([0.11163549, 0.70086036, 0.80284324, 0.77883859, 0.41044734,
       0.56486995, 0.74650569, 0.71343987, 0.21191136, 0.68550373])

In [67]:
np.random.rand(2,2)

array([[0.58347734, 0.87969217],
       [0.79595823, 0.5226433 ]])

In [68]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
arr1 = np.random.rand(9).reshape(3,3)

In [71]:
arr1

array([[0.38540609, 0.24942595, 0.73874102],
       [0.06714435, 0.74385981, 0.94744948],
       [0.00226367, 0.08734476, 0.66498587]])

In [72]:
arr1.ndim

2

In [73]:
# Indexing Arrays

In [74]:
array_1 = np.arange(1,15)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
array_1[2]

3

In [76]:
array_1[3]

4

In [77]:
array_1[0]

1

In [78]:
array_1[8]

9

In [79]:
array_1[2:8]

array([3, 4, 5, 6, 7, 8])

In [80]:
array_1[1:6]

array([2, 3, 4, 5, 6])

In [81]:
array_1[-3]

12

In [82]:
array_1[:-3]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
array_1[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [84]:
array_1[2:6]

array([3, 4, 5, 6])

In [85]:
array_1[2:5]

array([3, 4, 5])

In [86]:
array_1[1:4]

array([2, 3, 4])

In [87]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
array_2=[[1,2,3],[4,5,6],[7,8,9]]
array_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [89]:
np.array(array_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [91]:
np.arange(2,2,16)

array([], dtype=int32)

In [92]:
np.arange(2,2)

array([], dtype=int32)

In [93]:
x=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
x = np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
x.min()

1

In [95]:
x.max()

16

In [96]:
x.mean()

8.5

In [97]:
x.min(axis=0)

array([1, 2, 3, 4])

In [98]:
x.max(axis=0)

array([13, 14, 15, 16])

In [99]:
x.max(axis=1)

array([ 4,  8, 12, 16])

In [100]:
x.argmin()

0

In [101]:
x.argmax()

15

In [102]:
x.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [103]:
x.argmax(axis=1)

array([3, 3, 3, 3], dtype=int64)

In [104]:
x.reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [105]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [106]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [108]:
x.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])